//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOS_DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_Log
    {
        public int SEQ { get; set; }
        public System.DateTime OperateDate { get; set; }
        public System.TimeSpan OperateTime { get; set; }
        public string CompanyCD { get; set; }
        public string Processed_Program { get; set; }
        public string AccessPC { get; set; }
        public string OperateMode { get; set; }
        public string KeyItem { get; set; }
    }
}
