//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOS_DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Company
    {
        public string CompanyCD { get; set; }
        public string CompanyName { get; set; }
        public string Password { get; set; }
        public byte UserRole { get; set; }
        public string ShortName { get; set; }
        public string ZipCD1 { get; set; }
        public string ZipCD2 { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string TelephoneNo { get; set; }
        public string FaxNo { get; set; }
        public string PresidentName { get; set; }
        public byte RankingFlg { get; set; }
        public string InsertOperator { get; set; }
        public Nullable<System.DateTime> InsertDateTime { get; set; }
        public string UpdateOperator { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
    }
}
