//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOS_DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Item
    {
        public int MakerItemAdminCD { get; set; }
        public string MakerItemCD { get; set; }
        public string ItemName { get; set; }
        public string BrandCD { get; set; }
        public decimal ListPrice_WithoutTax_ { get; set; }
        public decimal ListPrice_InTax_ { get; set; }
        public decimal SalePrice_WithoutTax_ { get; set; }
        public decimal SalePrice_InTax_ { get; set; }
        public string GeneralClassName { get; set; }
        public string NormalClassName { get; set; }
        public string AdvenceClassName { get; set; }
        public Nullable<int> Lot { get; set; }
        public Nullable<int> ImageName { get; set; }
        public Nullable<int> Year { get; set; }
        public string Season { get; set; }
        public string CatelogNo { get; set; }
        public string InsertOperator { get; set; }
        public Nullable<System.DateTime> InsertDateTime { get; set; }
        public string UpdateOperator { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
    }
}
