//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOS_DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_MultiPorpose
    {
        public string ID { get; set; }
        public string KEY { get; set; }
        public string IDName { get; set; }
        public string text1 { get; set; }
        public string text2 { get; set; }
        public string text3 { get; set; }
        public string text4 { get; set; }
        public string text5 { get; set; }
        public Nullable<int> Num1 { get; set; }
        public Nullable<int> Num2 { get; set; }
        public Nullable<int> Num3 { get; set; }
        public Nullable<int> Num4 { get; set; }
        public Nullable<int> Num5 { get; set; }
        public Nullable<System.DateTime> Datetime1 { get; set; }
        public Nullable<System.DateTime> Datetime2 { get; set; }
        public Nullable<System.DateTime> Datetime3 { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string Updater { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
    }
}
