//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOS_DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_SKU
    {
        public int AdminCD { get; set; }
        public int MakerItemAdminCD { get; set; }
        public string SKUCD { get; set; }
        public string JANCD { get; set; }
        public string SizeName { get; set; }
        public string ColorName { get; set; }
        public int ZaikoSu { get; set; }
        public string InsertOperator { get; set; }
        public Nullable<System.DateTime> InsertDateTime { get; set; }
        public string UpdateOperator { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
    }
}
