//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOS_DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public string ID { get; set; }
        public string KEY { get; set; }
        public string Message1 { get; set; }
        public string Message2 { get; set; }
        public string Message3 { get; set; }
        public string Message4 { get; set; }
        public string Message5 { get; set; }
        public string Remark { get; set; }
        public string Creater { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Updater { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
