//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOS_DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OrderHeader
    {
        public string OrderID { get; set; }
        public Nullable<int> ShippingID { get; set; }
        public string ShippingName { get; set; }
        public string ZipCD1 { get; set; }
        public string ZipCD2 { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string TelephoneNO { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> ConsumptionTax { get; set; }
        public string Memo { get; set; }
        public string CustomerCD { get; set; }
        public Nullable<System.DateTime> OrderDateTime { get; set; }
        public string UpdateOperator { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
    }
}
